# The URL the site will be built for
base_url = "https://WekufuStudios.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

[languages.es]
build_search_index = true

[languages.ca]


[translations]
index_text = "We are currently working on Erebus, our first videogame, lear more about it "
here = "here"

games = "Games"
about_us = "About Us"

# Erebus page sections
features = "Features"
screenshots = "Screenshots"
download_demo = "Download demo"
available_on = "Available on"
contact_or_follow = "Contact or follow us"


[languages.es.translations]
index_text = "En estos momentos trabajamos en Erebus, nuestro primer videojuego, ¡descubre más "
here = "aquí"

games = "Juegos"
about_us = "Acerca de Nosotros"

# Erebus page sections
features = "Características"
screenshots = "Capturas"
download_demo = "Descarga la demo"
available_on = "Disponible en"
contact_or_follow = "Contáctanos o síguenos"


[languages.ca.translations]
index_text = "En aquests moments estem treballant en Erebus, el nostre primer videojoc, descobreix més "
here = "aquí"

games = "Jocs"
about_us = "Sobre nosaltres"

# Erebus page sections
features = "Característiques"
screenshots = "Captures de pantalla"
download_demo = "Descarga la demo"
available_on = "Disponible a"
contact_or_follow = "Contacte amb nosaltres o segueix-nos"