# The URL the site will be built for
base_url = "https://WekufuStudios.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# A list of glob patterns specifying asset files to ignore when the content
# directory is processed. Defaults to none, which means that all asset files are
# copied over to the `public` directory.
# Example:
#     ignored_content = ["*.{graphml,xlsx}", "temp.*", "**/build_folder"]
ignored_content = ["*.hx"]

# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true

# Whether to set rel="nofollow" for all external links
external_links_no_follow = true

# Whether to set rel="noreferrer" for all external links
external_links_no_referrer = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

[languages.es]
build_search_index = true

[languages.ca]


[translations]
index_text = "We are currently working on Erebus, our first videogame, lear more about it "
here = "here"

games = "Games"
about_us = "About Us"

jam_games = "Jam Games"
# Game descriptions
erebus_short_description = "You wake up in Erebus without any memories. Find answers as you explore this world, find equipment, and fight different enemies."

# Erebus page sections
#features = "Features"
#screenshots = "Screenshots"
#artwork = "Artwork"
#available_on = "Available on"
#contact_or_follow = "Contact or follow us"

# Where is the Princess wiki
examples = "Examples"
set_player_hp = "Set player hp"


[languages.es.translations]
index_text = "En estos momentos trabajamos en Erebus, nuestro primer videojuego, ¡descubre más "
here = "aquí"

games = "Juegos"
about_us = "Acerca de Nosotros"

jam_games = "Juegos Subidos en una Jam"
# Game descriptions
erebus_short_description = "Te despiertas en Erebus sin recordar nada. Encuentra respuestas mientras exploras este mundo, busca equipamiento, y lucha diferentes enemigos."

# Erebus page sections
#features = "Características"
#screenshots = "Capturas"
#artwork = "Arte conceptual"
#available_on = "Disponible en"
#contact_or_follow = "Contáctanos o síguenos"


[languages.ca.translations]
index_text = "En aquests moments estem treballant en Erebus, el nostre primer videojoc, descobreix més "
here = "aquí"

games = "Jocs"
about_us = "Sobre nosaltres"

jam_games = "Jocs Publicats en una Jam"
# Game descriptions
erebus_short_description = "Et despertes a Erebus sense recordar res. Troba respostes mentre explores aquest món, busca equipament, i enfrontat a diferents enemics."

# Erebus page sections
#features = "Característiques"
#screenshots = "Captures de pantalla"
#artwork = "Art conceptual"
#available_on = "Disponible a"
#contact_or_follow = "Contacte amb nosaltres o segueix-nos"